# Generated by Django 4.0 on 2023-07-25 11:06

from django.db import migrations, models
import django.db.models.deletion
import log_actions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_speciality_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время события')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='object id')),
                ('action', models.TextField(verbose_name='Действие')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.kaifarikuser')),
            ],
            managers=[
                ('manager_log', log_actions.models.LogManager()),
            ],
        ),
    ]
