# Generated by Django 4.0 on 2023-07-25 11:57

from django.db import migrations, models
import log_actions.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_speciality_role'),
        ('log_actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='logactions',
            managers=[
                ('objects', log_actions.models.LogManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='logactions',
            name='role',
        ),
        migrations.AddField(
            model_name='logactions',
            name='role',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
